// import { Poppins} from 'next/font/google'
// import './globals.css';

// const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '700'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className="scroll-smooth">
//       <body className={poppins.className}>
//         <main className="mx-auto max-w-7xl ">
//             {children}
    
//         </main>
//       </body>
//     </html>
//   )
// }



// import {AppProvider} from "@/components/AppContext";

import { Roboto } from 'next/font/google';
import './globals.css'
import './layout.css'
import {Toaster} from "react-hot-toast";
import { AppProvider } from '../components/AppContext';
import Header from "../components/Header/header";
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
      
        <main>
          <AppProvider>  
          {children}
          <Toaster/>
          <Header/>
          </AppProvider>
        </main>
      </body>
    </html>
  )
}